### ISSUE TITLE
Response::send: setting Cache-Control header twice

### ISSUE THREAD

**Issue by distantnative** [k-next/http#2]
In line 118 and 120 (https://github.com/k-next/http/blob/master/src/HTTP/Response/Download.php#L118-L120) the `Cache-Control` header is defined twice but differently. Of course only the `private` value lasts.

**Comment by lukasbestle** [comment]
What was actually supposed to be set here?

Neither value prevents caching. The first one tells the cache to verify the cache before serving it, the second one tells the cache that it may only cache the result if the cache belongs to the user directly.

**Comment by distantnative** [comment]
@bastianallgeier needs to answer that question :D

**Comment by bastianallgeier** [comment]
Quite possible that I just got this from an example on php.net years ago. I copied this one over from the old toolkit method in the header class. Let's clean it up!
